## Create a logistic regression to predict absenteeism

### Import the relevant libraries

In [19]:
import pandas as pd
import numpy as np

### Load the data

In [20]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [21]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

### Create the targets

In [22]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [23]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median() , 1,0)

In [24]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [25]:
data_preprocessed ['Excessive Absenteeism'] = targets

In [26]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### A comment on the target

In [27]:
targets.sum()/ targets.shape[0]

0.45571428571428574

In [28]:
data_with_targets =data_preprocessed.drop (['Absenteeism Time in Hours'], axis = 1)

In [29]:
data_with_targets is data_preprocessed

False

### Select the inputs for regression

In [30]:
data_with_targets.shape

(700, 15)

In [31]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [35]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [80]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

### Standardise the Data

In [41]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [42]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [43]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [44]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [45]:
scaled_inputs.shape

(700, 14)

### Split the data into test and train data

In [48]:
from sklearn.model_selection import train_test_split


In [58]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs, targets,train_size = 0.8,random_state = 20)

In [59]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [60]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


### Logistic Regression with sklearn

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model

In [62]:
reg = LogisticRegression()

In [63]:
reg.fit(x_train,y_train)

LogisticRegression()

In [64]:
reg.score(x_train,y_train)

0.7803571428571429

#### Manually check the accuracy

In [67]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [68]:
np.sum(model_outputs == y_train)

437

In [70]:
model_outputs.shape[0]

560

In [71]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.7803571428571429

#### Finding the intercepts and coefficients

In [73]:
reg.intercept_

array([-0.21102398])

In [76]:
reg.coef_

array([[ 2.06986858,  0.33028689,  1.56236468,  1.31054482,  0.02588386,
        -0.08649155,  0.72352943, -0.06072562, -0.2052754 , -0.02828267,
         0.3257168 , -0.16073453,  0.3815691 , -0.32129179]])

In [82]:
feature_name = unscaled_inputs.columns.values

#### Creating the summary table

In [83]:
summary_table = pd.DataFrame(columns =['Feature name'],data = feature_name)

In [85]:
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.069869
1                  Reason_2     0.330287
2                  Reason_3     1.562365
3                  Reason_4     1.310545
4               Month Value     0.025884
5           Day of the Week    -0.086492
6    Transportation Expense     0.723529
7          Distance to Work    -0.060726
8                       Age    -0.205275
9   Daily Work Load Average    -0.028283
10          Body Mass Index     0.325717
11                Education    -0.160735
12                 Children     0.381569
13                      Pet    -0.321292

Adding the y intercept

In [86]:
summary_table.index = summary_table.index + 1

In [88]:
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.211024
1                  Reason_1     2.069869
2                  Reason_2     0.330287
3                  Reason_3     1.562365
4                  Reason_4     1.310545
5               Month Value     0.025884
6           Day of the Week    -0.086492
7    Transportation Expense     0.723529
8          Distance to Work    -0.060726
9                       Age    -0.205275
10  Daily Work Load Average    -0.028283
11          Body Mass Index     0.325717
12                Education    -0.160735
13                 Children     0.381569
14                      Pet    -0.321292

In [90]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [95]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.069869    7.923782
3                  Reason_3     1.562365    4.770088
4                  Reason_4     1.310545    3.708193
7    Transportation Expense     0.723529    2.061697
13                 Children     0.381569    1.464581
2                  Reason_2     0.330287    1.391367
11          Body Mass Index     0.325717    1.385023
5               Month Value     0.025884    1.026222
10  Daily Work Load Average    -0.028283    0.972114
8          Distance to Work    -0.060726    0.941081
6           Day of the Week    -0.086492    0.917143
12                Education    -0.160735    0.851518
9                       Age    -0.205275    0.814423
0                 Intercept    -0.211024    0.809755
14                      Pet    -0.321292    0.725212

In [96]:
columns_to_omit = ['Reason_1','Reason_2','Reason_3','Reason_4','Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [97]:
reg.score(x_test,y_test)

0.7285714285714285

In [99]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.76471409, 0.23528591],
       [0.61167855, 0.38832145],
       [0.40767059, 0.59232941],
       [0.78557457, 0.21442543],
       [0.06075314, 0.93924686],
       [0.26771935, 0.73228065],
       [0.28626672, 0.71373328],
       [0.06687796, 0.93312204],
       [0.75878872, 0.24121128],
       [0.76521137, 0.23478863],
       [0.47338669, 0.52661331],
       [0.13567347, 0.86432653],
       [0.04163776, 0.95836224],
       [0.69555394, 0.30444606],
       [0.20586587, 0.79413413],
       [0.47708783, 0.52291217],
       [0.49325552, 0.50674448],
       [0.5385909 , 0.4614091 ],
       [0.37778738, 0.62221262],
       [0.02923023, 0.97076977],
       [0.7340362 , 0.2659638 ],
       [0.77718245, 0.22281755],
       [0.4260149 , 0.5739851 ],
       [0.44253864, 0.55746136],
       [0.15300393, 0.84699607],
       [0.76013758, 0.23986242],
       [0.45641034, 0.54358966],
       [0.89837466, 0.10162534],
       [0.16321201, 0.83678799],
       [0.76855864, 0.23144136],
       [0.

In [100]:
predicted_proba [:,1]

array([0.23528591, 0.38832145, 0.59232941, 0.21442543, 0.93924686,
       0.73228065, 0.71373328, 0.93312204, 0.24121128, 0.23478863,
       0.52661331, 0.86432653, 0.95836224, 0.30444606, 0.79413413,
       0.52291217, 0.50674448, 0.4614091 , 0.62221262, 0.97076977,
       0.2659638 , 0.22281755, 0.5739851 , 0.55746136, 0.84699607,
       0.23986242, 0.54358966, 0.10162534, 0.83678799, 0.23144136,
       0.41408328, 0.74153958, 0.7008613 , 0.52928416, 0.22281755,
       0.61594634, 0.25772832, 0.83185767, 0.47494375, 0.60672861,
       0.2424275 , 0.41695579, 0.23470549, 0.09844889, 0.82776712,
       0.73210957, 0.76165752, 0.24123202, 0.27215577, 0.20124285,
       0.49892458, 0.07038119, 0.70505423, 0.26216528, 0.8684819 ,
       0.44148327, 0.95231371, 0.29202077, 0.07809625, 0.07661661,
       0.74434135, 0.68006647, 0.28705942, 0.85845493, 0.23884712,
       0.23733866, 0.01167321, 0.24484425, 0.8442063 , 0.31178283,
       0.24389933, 0.07867904, 0.92229144, 0.46714437, 0.65160

#### Save the model

In [101]:
import pickle

In [102]:
with open ('model', 'wb') as file:
    pickle.dump(reg,file)

In [ ]:
with open ('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler,file)